apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /__/metrics
    prometheus.io/port: '8081'
  name: kafka-topic-applier
  labels:
    app.kubernetes.io/name: kafka-topic-applier
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 8090
  selector:
    app.kubernetes.io/name: kafka-topic-applier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-applier
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-topic-applier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-topic-applier
    spec:
      containers:
        - name: kafka-topic-applier
          image: quay.io/utilitywarehouse/kafka-topic-applier:v1.0.0-RC1
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 0m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /__/ready
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /__/ready
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
          ports:
            - containerPort: 8081
              name: metrics
            - containerPort: 8090
              name: grpc
          env:
            - name: TOPICS_FILE
              value: /tmp/kta/topics.yaml
            - name: GRPC_PORT
              value: '8090'
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-brokers
                  key: internal.kafka.brokers
            - name: KAFKA_VERSION
              valueFrom:
                configMapKeyRef:
                  name: kafka-brokers
                  key: internal.kafka.broker.version
          volumeMounts:
            - name: kafka-topics
              mountPath: /tmp/kta
      volumes:
        - configMap:
            defaultMode: 420
            name: kafka-topics
          name: kafka-topics
