apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /__/metrics
    prometheus.io/port: '8081'
  name: &app kafka-topic-applier
  labels:
    app: *app
spec:
  ports:
    - name: ops
      protocol: TCP
      port: 8081
    - name: grpc
      protocol: TCP
      port: 8090
  selector:
    app: *app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-applier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topic-applier
  template:
    metadata:
      labels:
        app: kafka-topic-applier
    spec:
      imagePullSecrets:
        - name: dockerhub-key
      containers:
        - name: kafka-topic-applier
          image: registry.uw.systems/billing/kafka-topic-applier:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /__/ready
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /__/ready
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
          ports:
            - containerPort: 8081
              name: metrics
            - containerPort: 8090
              name: grpc
          env:
            - name: OPS_PORT
              value: '8081'
            - name: TOPICS_FILE
              value: /tmp/kta/topics.yaml
            - name: GRPC_PORT
              value: '8090'
            - name: LOG_LEVEL
              value: info
            - name: TEAM
              value: billing
            - name: LOG_FORMAT
              value: json
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-brokers
                  key: internal.kafka.brokers
            - name: KAFKA_VERSION
              valueFrom:
                configMapKeyRef:
                  name: kafka-brokers
                  key: internal.kafka.broker.version
          volumeMounts:
            - name: kafka-topics
              mountPath: /tmp/kta
      volumes:
        - configMap:
            defaultMode: 420
            name: kafka-topics
          name: kafka-topics
