version: 2
jobs:
  build:
    working_directory: ~/app/kafka-topic-applier
    docker:
    - image: circleci/golang:1
    
    
    steps:
      - checkout
      
      
      - run: git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: make install
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: make lint test
      - setup_remote_docker
      - run: make ci-docker-build
workflows:
  version: 2
  development:
    jobs:
      - build:
          context: billing
