apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-applier
spec:
  template:
    spec:
      containers:
        - name: kafka-topic-applier
          image: registry.uw.systems/billing/kafka-topic-applier:latest
          env:
            - name: EQDB_LOADER_BIGQUERY_PROJECT_ID
              value: uw-net
