apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/utilitywarehouse/kafka-topic-applier//manifests/base?ref=master
configMapGenerator:
  - name: kafka-topics
    files:
      - topics.yaml
patchesStrategicMerge:
  - app.yaml
