apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/utilitywarehouse/kafka-topic-applier//manifests/base?ref=master
configMapGenerator:
  - files:
      - topics.yaml
    name: kafka-topics
patches:
  - path: app.yaml
